"""add_supplier_opening_balance_type

Revision ID: a5e87f75ee17
Revises: 1a279cb17dd6
Create Date: 2026-04-20 19:07:08.400399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e87f75ee17'
down_revision: Union[str, None] = '1a279cb17dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('opening_balance_type', sa.Enum('payable', 'receivable', name='balance_type'), server_default=sa.text("'payable'::balance_type"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'opening_balance_type')
    # ### end Alembic commands ###
